replicaCount: 1

bots:
  - name: bdellovibrio
    script: bdellovibrio_bot.py
  - name: bambi
    script: bambi_bot.py

image:
  repository: your-container-image
  tag: latest
  pullPolicy: IfNotPresent

volumeMounts:
  - name: tokens-storage
    mountPath: /tokens

volumes:
  - name: tokens-storage
    persistentVolumeClaim:
      claimName: tokens-pvc
