apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/k3s/flux-system/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: BioinfCommunityDiscordBots
  validation: client
