apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k3s/storage/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: BioinfCommunityDiscordBots
