apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bots-pvc
  namespace: discord-bots
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: discord-bots-volume
  storageClassName: longhorn
