apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: your-bot-image:latest
          envFrom:
            - configMapRef:
                name: bot-config
