apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: discord-bot
  namespace: default
spec:
  releaseName: discord-bot
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: discord-bots-repo
        namespace: flux-system
      interval: 5m
