apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: discord-bot
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/k3s/discord-bot/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: BioinfCommunityDiscordBots
