apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tokens-pvc
  namespace: discord-bots
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
